### ISSUE TITLE
[質問]書籍の正誤表

### ISSUE THREAD

**Issue by rkarsnk** [moonmile/net5-samples#1]
書籍第1版を購入したものですが、書籍の正誤表はどこかにあるでしょうか？

**Comment by moonmile** [comment]
いまのところ正誤表はありません。
[\.NET 5プログラミング入門｜日経の本 日経BP](https://www.nikkeibp.co.jp/atclpubmkt/book/21/S80020/)

ミスを見つけたら、私のブログ https://www.moonmile.net/blog/ に投げて貰えると返答が早かったりします。
